=== de-rish/drv-adapter/drv-xml-model/src/main/schema/vereinsliste_v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:dvl="http://schemas.rudern.de/vereinsliste/2008/" targetNamespace="http://schemas.rudern.de/vereinsliste/2008/">
	<annotation>
		<documentation>DRV Vereinsliste - abrufbar unter http://verwaltung.rudern.de/vereine.php?t=xml2</documentation>
	</annotation>
	<complexType name="tVereine">
		<sequence>
			<element name="verein" type="dvl:tVerein" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="erstellt" type="dateTime"/>
	</complexType>
	<complexType name="tVerein">
		<sequence>
			<element name="name" type="string"/>
			<element name="ort" type="string"/>
			<element name="kurzform" type="string"/>
			<element name="lettern" type="string"/>
			<any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="nonNegativeInteger"/>
		<anyAttribute namespace="##other" processContents="lax"/>
	</complexType>
	<element name="vereine" type="dvl:tVereine"/>
</schema>

=== de-rish/drv-adapter/drv-xml-parser/src/test/resources/vereine-to-parse.xml
<?xml version="1.0" encoding="UTF-8"?>
<dvl:vereine xmlns:dvl="http://schemas.rudern.de/vereinsliste/2008/" erstellt="2022-12-23T20:36:49+01:00"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://schemas.rudern.de/vereinsliste/2008/ http://schemas.rudern.de/vereinsliste_v2.xsd">
	<verein id="10001">
		<name>testVereinsName1</name>
		<ort>testVereinsOrt1</ort>
		<kurzform>testVereinsKurzform1</kurzform>
		<lettern>testVereinsLettern1</lettern>
	</verein>
	<verein id="11000">
		<name>testVereinsName2</name>
		<ort>testVereinsOrt2</ort>
		<kurzform>testVereinsKurzform2</kurzform>
		<lettern>testVereinsLettern2</lettern>
	</verein>
</dvl:vereine>
